### ISSUE TITLE
Switch from Mocha to Jest for "Better" testing

### ISSUE THREAD

**Issue by KamalAman** [rolftimmermans/event-iterator#14]
I find the Jest runtime more enjoyable than mocha for a few reasons: 

Assertions and reporting
Mocking (which much simplify some of the current unit tests)
Parallel processing
 
Would do accept a PR that will migrate?

**Comment by rolftimmermans** [comment]
Sure! I'm not bound to any particular testing framework, so whatever works best is fine.

The only thing I personally dislike is a DSL for assertions like `expect(a + b).not.toBe(0)` which IMHO obscure what is being asserted. I like chai's [assertion](https://www.chaijs.com/api/assert/) library personally... 🤷‍♀

**Comment by rolftimmermans** [comment]
I'd be happy to accept PRs that change the test suite for the better, but closing this for now since changing test framework is not a goal in itself.
