### ISSUE TITLE
Multiple iterator consumers edge case

### ISSUE THREAD

**Issue by KamalAman** [rolftimmermans/event-iterator#9]
First, excellent library! 

If the queue it empty, and `.next` is called multiple times before the queue fills up, all n-1 calls with never be resolved.

```js
    const event = new EventEmitter();
    const iterator = stream.call(event)[Symbol.asyncIterator]();

    const requests = Promise.all([
      iterator.next(),
      iterator.next(),
    ]);

    event.emit('data', 'a');
    event.emit('data', 'b');

    // Will hang here since the first promise placeholder will never be resolved
    const result = await requests;
    expect(result).toEqual([{ value: 'a' }, { value: 'b' }]);
```

If you swap the orderer of emitting the events and the Promise.all, it will succeed

The placeholder needs to be replaced with a `pullQueue`. 
When next is called and there is nothing in the `queue`, push a promise into the `pullQueue`.
When you hear an event, check the `pullQueue` first. Resolve the next promise in the `pullQueue` otherwise push the value into the `queue`.

I would also rename `queue` to `pushQueue`

**Comment by rolftimmermans** [comment]
Perfect, thanks!
